<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DeskButler.Core\DeskButler.Core.csproj" />
    <ProjectReference Include="..\DeskButler.Application\DeskButler.Application.csproj" />
    <ProjectReference Include="..\DeskButler.Persistence\DeskButler.Persistence.csproj" />
    <ProjectReference Include="..\DeskButler.Infrastructure.Windows\DeskButler.Infrastructure.Windows.csproj" />
    <ProjectReference Include="..\DeskButler.Modules.WorkspaceRecovery\DeskButler.Modules.WorkspaceRecovery.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\DeskButler.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\DeskButler.ico" />
  </ItemGroup>

</Project>
