<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\DeskButler.Core\DeskButler.Core.csproj" />
    <ProjectReference Include="..\..\..\..\src\DeskButler.Persistence\DeskButler.Persistence.csproj" />
    <ProjectReference Include="..\..\..\..\src\DeskButler.Modules.WorkspaceRecovery\DeskButler.Modules.WorkspaceRecovery.csproj" />
  </ItemGroup>
</Project>
